import { Button, StandardButton } from "std-widgets.slint";

export component homeView
{ 
    // Callbacks
    callback start_clicked();
    callback settings_clicked();
    callback quit_clicked();


    VerticalLayout {
        alignment: center;

        Text 
        {
            text: "Hangman";
            horizontal-alignment: center;
            letter-spacing: 10px;
            color: #3E2723;
            font-italic: true;
            font-family: "Comic Sans MS";
            font-weight: 300;
        }
    
        VerticalLayout 
        {  
            Button {
                text: "Start";
                clicked => root.start_clicked();
            }

            Button {
                text: "Settings";

                clicked => root.settings_clicked();
            }

            Button {
                text: "Quit";

                clicked => root.quit_clicked();
            }
        }
    }
}